apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  description: Minimal placeholder pipeline for ShopCarts; tasks to be added later.
  params:
    - name: APP_NAME
      description: Application name used for Kubernetes resources
      type: string
    - name: GIT_REPO
      description: Git repository to clone
      type: string
    - name: IMAGE_NAME
      description: Fully qualified image repository
      type: string
    - name: GIT_REVISION
      description: Git revision to build
      type: string
      default: main
    - name: BASE_URL
      description: Base URL of the deployed service (Route hostname) for BDD tests
      type: string
  workspaces:
    - name: pipeline-workspace
      description: Shared workspace for source, manifests, and build context
    - name: dockerconfig
      description: Docker registry config (config.json) for kaniko

  tasks:
    # Clone repository into shared workspace
    - name: clone
      taskRef:
        name: git-clone
        kind: Task
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: pipeline-workspace

    # Build and push Docker image once using Tekton Hub kaniko Task,
    # tagging it with both the Git commit SHA and latest.
    - name: build-image
      runAfter:
        - clone
      taskRef:
        name: kaniko
        kind: Task
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME):$(tasks.clone.results.commit)
        - name: EXTRA_ARGS
          value:
            - --destination=$(params.IMAGE_NAME):latest
      workspaces:
        - name: source
          workspace: pipeline-workspace
        - name: dockerconfig
          workspace: dockerconfig

    # Run BDD tests using behave task
    - name: bdd-tests
      runAfter:
        - build-image
      taskRef:
        name: behave
        kind: Task
      params:
        - name: base-url
          value: $(params.BASE_URL)
      workspaces:
        - name: source
          workspace: pipeline-workspace
