apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: shopcarts-pipeline
spec:
  params:
    - name: repo-url
      type: string
      description: Git repository URL
    - name: revision
      type: string
      description: Branch name or commit SHA to checkout
      default: master
  workspaces:
    - name: source

  tasks:
    # Clone repository from GitHub into shared workspace
    - name: clone
      taskRef:
        name: git-clone
        kind: Task
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: source

    # Run linting checks (flake8 and pylint)
    # TODO: Task definition 'lint-task' needs to be created
    - name: lint
      runAfter: ["clone"]
      taskRef:
        name: lint-task
        kind: Task
      workspaces:
        - name: source
          workspace: source

    # Run unit tests with pytest
    # TODO: Task definition 'test-task' needs to be created
    - name: test
      runAfter: ["clone"]
      taskRef:
        name: test-task
        kind: Task
      workspaces:
        - name: source
          workspace: source

    # Build Docker image from source code
    # TODO: Task definition 'build-image-task' needs to be created
    - name: build-image
      runAfter: ["clone", "lint", "test"]
      taskRef:
        name: build-image-task
        kind: Task
      workspaces:
        - name: source
          workspace: source

    # Deploy application to Kubernetes cluster
    # TODO: Task definition 'deploy-task' needs to be created
    - name: deploy
      runAfter: ["build-image"]
      taskRef:
        name: deploy-task
        kind: Task
      workspaces:
        - name: source
          workspace: source

    # Run BDD tests against deployed application
    # TODO: Task definition 'bdd-task' needs to be created
    # TODO: BASE_URL environment variable needs to be set by EventListener or PipelineRun
    - name: bdd-tests
      runAfter: ["deploy"]
      taskRef:
        name: bdd-task
        kind: Task
      workspaces:
        - name: source
          workspace: source
      env:
        - name: BASE_URL
          value: ""  # TODO: Set to actual service route URL