apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: shopcarts-pipeline
spec:
  params:
    - name: repo-url
      type: string
      description: Git repository URL
    - name: revision
      type: string
      description: Branch name or commit SHA to checkout
      default: master
  workspaces:
    - name: source

  tasks:
    - name: clone-source
      taskRef:
        name: git-clone
        kind: Task
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: source